### ISSUE TITLE
undefined symbol: npy_log1pf

### ISSUE THREAD

**Issue by Jonah16-hub** [smuecke/qubolite#9]
Hi,

Installing qubolite on a new venv (Python 3.10.6, Numpy 1.23.5, Linux RedHat Enterprise 8.8) I got this error :

```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File " ~ /jaubertj/venv-qubolite/lib/python3.10/site-packages/qubolite-0.8.5-py3.10-linux-x86_64.egg/qubolite/__init__.py", line 1, in <module>
    from .qubo import (
  File " ~ /jaubertj/venv-qubolite/lib/python3.10/site-packages/qubolite-0.8.5-py3.10-linux-x86_64.egg/qubolite/qubo.py", line 11, in <module>
    from _c_utils import brute_force as _brute_force_c
ImportError:  ~ /jaubertj/venv-qubolite/lib/python3.10/site-packages/qubolite-0.8.5-py3.10-linux-x86_64.egg/_c_utils.cpython-310-x86_64-linux-gnu.so: undefined symbol: npy_log1pf
```

while importing qubolite, but, import numpy works nice.

Does someone understand how to solve it ?

Thanks,

Jonah

**Comment by Jonah16-hub** [comment]
Trying with a new venv Python 3.8.10, Numpy 1.23.5 and get this :

```python
running install
running bdist_egg
running egg_info
writing UNKNOWN.egg-info/PKG-INFO
writing dependency_links to UNKNOWN.egg-info/dependency_links.txt
writing top-level names to UNKNOWN.egg-info/top_level.txt
listing git files failed - pretending there aren't any
reading manifest file 'UNKNOWN.egg-info/SOURCES.txt'
writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-3.8/_c_utils.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
creating stub loader for _c_utils.cpython-38-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/_c_utils.py to _c_utils.cpython-38.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying UNKNOWN.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying UNKNOWN.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying UNKNOWN.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying UNKNOWN.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
__pycache__._c_utils.cpython-38: module references __file__
creating 'dist/UNKNOWN-0.0.0-py3.8-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing UNKNOWN-0.0.0-py3.8-linux-x86_64.egg
removing ' ~ /jaubertj/venv3.8.10/lib/python3.8/site-packages/UNKNOWN-0.0.0-py3.8-linux-x86_64.egg' (and everything under it)
creating  ~ /jaubertj/venv3.8.10/lib/python3.8/site-packages/UNKNOWN-0.0.0-py3.8-linux-x86_64.egg
Extracting UNKNOWN-0.0.0-py3.8-linux-x86_64.egg to  ~ /jaubertj/venv3.8.10/lib/python3.8/site-packages
UNKNOWN 0.0.0 is already the active version in easy-install.pth

Installed  ~ /jaubertj/venv3.8.10/lib/python3.8/site-packages/UNKNOWN-0.0.0-py3.8-linux-x86_64.egg
Processing dependencies for UNKNOWN==0.0.0
Finished processing dependencies for UNKNOWN==0.0.0
```

by doing python3 setup.py install. So he not recognize my Python version and environment ?

**Comment by Jonah16-hub** [comment]
Trying with Python 3.10.6 and Numpy 1.24.4 and getting the same undefined symbol npy_log1pf
